### PR TITLE
Add extra attributes for devices when connected to network

### LINKED ISSUE #25: Is it possible t track which Eero a device is connected to?
I have been doing some searching but can't find a way to do this.

I have one Eero pro downstairs and one upstairs. Is it possible to trigger events based on which Eero my phone is connected to?

Thanks!

### PR DESCRIPTION
**Pull request by schmittx**
Adds extra attributes for `network_name`, `connected_to`, `ip_address`, and `mac`.

Fixes #25.

### CODE REVIEW

**Comment by rsnodgrass** [comment]
Looks good, thanks for the contribution!

**Comment by schmittx** [comment]
Glad to help! Any chance I can get some Hacktoberfest credit as well? The PR just needs to be labeled as `hacktoberfest-accepted` ([more info](https://hacktoberfest.digitalocean.com/hacktoberfest-update))

**Comment by jrlucier** [comment]
Thanks for the contribution!  I'll validate it tonight against the latest HASS and merge in if everything looks good.  I've tagged the project as being within Hacktoberfest, so you should get credit ;)

**Comment by schmittx** [comment]
The scanner-based device tracker platform doesn't allow extra attributes to be removed when the entity is not `not_home`.

It's admittedly weird to see `connected_to` in attributes when the entity is `not_home` so I'd like to find a workaround at some point (if possible), but I think it's not a show-stopper at the moment.

**Pull request closed without merging**
